[package]
name = "htmlhl"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11.2"
tree-sitter = "0.25.10"
tree-sitter-highlight = "0.25.10"
tree-sitter-javascript = "0.25.0"
tree-sitter-python = "0.25.0"
tree-sitter-rust = "0.24.0"
